spring.application.name=application

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tokuhub_api_db}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASS:password123}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Seguridad inicial
spring.security.user.name=admin
spring.security.user.password=password123

# Perfil activo por defecto
spring.profiles.active=dev